Feature: Temporary Placement Request

        The platform allows the agency user to create a Temporary contract via self serve request.
        To Implement this feature, Self service toggle should be enabled at agency entity level.

        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client and <paymentType> payment company selected by agency user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                And Select the "<paymentType>" payment company by agency user in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and existing client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                Then Review and Approve the temporary placement by client hiring manager user
                * Review and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client, new contacts and <paymentType> payment company selected by agency user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                And Select the "<paymentType>" payment company by agency user in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                And Setup the new client contracts given in temp request in the raise platform
                Then Review and Approve the temporary placement by client hiring manager user
                *  Review and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"

                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |

        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client and <paymentType> payment company selected by contractor user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>-<unitType>" placement details and existing client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                Then Review and Approve the temporary placement by client hiring manager user
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |
        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client, new contacts and <paymentType> payment company selected by contractor user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                And Setup the new client contracts given in temp request in the raise platform
                Then Review and Approve the temporary placement by client hiring manager user
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |

        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency for New contractor with New client and New <paymentType> payment company selected by contractor user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Fill the New "<paymentType>" contractor details in the temp request form
                Then Fill the New Client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in awaiting raise approval status
                * login as Onboarding agent Maker user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                And Onboard the new client generated for the temp request
                Then Review and Approve the temporary placement by client hiring manager user
                * Fill the New "<paymentType>" Payment Company in the temporary placement by contractor user
                * Accept the temporary placement by contractor user with Newly Updated "<paymentType>" Payment Company
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |

        @E2E
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency for New contractor with New client and New <paymentType> payment company selected by agency user
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Fill the New "<paymentType>" contractor details in the temp request form
                * Select the New "<paymentType>" Payment Company in the temp request by agency user
                Then Fill the New Client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in awaiting raise approval status
                * login as Onboarding agent Maker user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                And Onboard the new client generated for the temp request
                Then Review and Approve the temporary placement by client hiring manager user
                * Accept the temporary placement by contractor user with Newly Updated "<paymentType>" Payment Company
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |

        <--- Client User Approval via magic link --->
        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client and <paymentType> payment company selected by agency user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                And Select the "<paymentType>" payment company by agency user in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>-<unitType>" placement details and existing client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client, new contacts and <paymentType> payment company selected by agency user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                And Select the "<paymentType>" payment company by agency user in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                And Setup the new client contracts given in temp request in the raise platform
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |

        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client, new contacts and <paymentType> payment company selected by contractor user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                And Setup the new client contracts given in temp request in the raise platform
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |

        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency mapped existing contractor with existing client and <paymentType> payment company selected by contractor user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Select the Existing "<paymentType>" contractor details in the temp request form
                Then Select the Existing client details in the temp request form
                Then Fill the "<timesheetFrequency>-<unitType>" placement details and existing client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in client pending approval status
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Select the Existing "<paymentType>" Payment Company and Accept the temporary placement by contractor user
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |

        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency for New contractor with New client and New <paymentType> payment company selected by contractor user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Fill the New "<paymentType>" contractor details in the temp request form
                Then Fill the New Client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in awaiting raise approval status
                * login as Onboarding agent Maker user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                And Onboard the new client generated for the temp request
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Fill the New "<paymentType>" Payment Company in the temporary placement by contractor user
                * Accept the temporary placement by contractor user with Newly Updated "<paymentType>" Payment Company
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |
                        | Direct       | Hours    | Weekly             | Funded      | Limited     |
                        | Direct       | Hours    | Monthly            | Funded      | Limited     |
                        | Direct       | Days     | Weekly             | Funded      | Limited     |
                        | Direct       | Days     | Monthly            | Funded      | Limited     |
                        | Indirect     | Hours    | Weekly             | Funded      | Limited     |
                        | Indirect     | Hours    | Monthly            | Funded      | Limited     |
                        | Indirect     | Days     | Weekly             | Funded      | Limited     |
                        | Indirect     | Days     | Monthly            | Funded      | Limited     |

        @E2E @magicLink
        Scenario Outline: Create a <timesheetFrequency>-<unitType> temporary placement request for <fundingModel> model agency for New contractor with New client and New <paymentType> payment company selected by agency user (client approval via magic link)
                Given "<paymentType>" contractor and "<fundingModel>" model entities details to create a temp request
                Then "<fundingModel>" model Agency business is allowed to make a self serve request for temporary placement
                Then login as agency user to create a new temporary placement request
                And navigate to the temporary placement request list page
                Then Fill the New "<paymentType>" contractor details in the temp request form
                * Select the New "<paymentType>" Payment Company in the temp request by agency user
                Then Fill the New Client details in the temp request form
                Then Fill the "<timesheetFrequency>"-"<unitType>" placement details and new client contacts in the temp request form
                When The Agency user Review and Submit the temporary placement request details
                Then Temporary placement is generated for the Submitted request in awaiting raise approval status
                * login as Onboarding agent Maker user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                And Onboard the new client generated for the temp request
                Then Review and Approve the temporary placement by client hiring manager user via magic link
                * Accept the temporary placement by contractor user with Newly Updated "<paymentType>" Payment Company
                Then login as Credit Risk Assistant user
                And navigate to the temporary placement list page
                * select the respective temporary placement
                When The Credit Risk Assistant user reviews and accepts the temporary placement
                Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
                Examples:
                        | fundingModel | unitType | timesheetFrequency | fundingType | paymentType |
                        | Direct       | Hours    | Weekly             | Funded      | Umbrella    |
                        | Direct       | Hours    | Monthly            | Funded      | Umbrella    |
                        | Direct       | Days     | Weekly             | Funded      | Umbrella    |
                        | Direct       | Days     | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Hours    | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Hours    | Monthly            | Funded      | Umbrella    |
                        | Indirect     | Days     | Weekly             | Funded      | Umbrella    |
                        | Indirect     | Days     | Monthly            | Funded      | Umbrella    |