Feature: Temporary Placement

    Background: The user is logged into the raise portal and navigated to the temporary placement list page
        Given login as Onboarding agent Maker user
        Then navigate to the temporary placement list page

    @focus @E2E
    Scenario Outline: Create a temporary placement for <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and approved by internal users on behalf of external users
        Given temporary placement details
        Then select the funding type "<fundingType>" in temporary placement form
        And select the currency in the temporary placement form
        * select the "<fundingModel>" model agency in the temporary placement form
        * select the "<fundingModel>" model client in the temporary placement form
        * select the "<fundingModel>" model contractor in the temporary placement form
        * fill the placement details in the temporary placement form
        * select the "<timesheetFrequency>" frequency in the temporary placement form
        * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
        * Add the Additional rate according to the unit type-"<unitType>" in the temporary placement form, if required
        Then Submit the temporary placement for Agency Approval
        * upload the Proof for Agency Approval-Rejection for the temporary placement
        And Approve the temporary placement on behalf of Agency user
        * upload the Proof for Client Approval-Rejection for the temporary placement
        * Approve the temporary placement on behalf of Client user
        * upload the Proof for Contractor Approval-Rejection for the temporary placement
        * Accept the temporary placement on behalf of Contractor user
        Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
        Examples:
            | fundingType | fundingModel | unitType | timesheetFrequency |
            | Funded      | Direct       | Hours    | Weekly             |
            | Funded      | Direct       | Hours    | Monthly            |
            | Funded      | Direct       | Days     | Weekly             |
            | Funded      | Direct       | Days     | Monthly            |
            | Funded      | Indirect     | Hours    | Weekly             |
            | Funded      | Indirect     | Hours    | Monthly            |
            | Funded      | Indirect     | Days     | Weekly             |
            | Funded      | Indirect     | Days     | Monthly            |
    # | Paid When Paid | Direct       | Hours    | Weekly             |
    # | Paid When Paid | Direct       | Hours    | Monthly            |
    # | Paid When Paid | Direct       | Days     | Weekly             |
    # | Paid When Paid | Direct       | Days     | Monthly            |
    # | Paid When Paid | Indirect     | Hours    | Weekly             |
    # | Paid When Paid | Indirect     | Hours    | Monthly            |
    # | Paid When Paid | Indirect     | Days     | Weekly             |
    # | Paid When Paid | Indirect     | Days     | Monthly            |

#     @focus @E2E
#     Scenario Outline: Create a temporary placement for <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and approved by external users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |

#     @focus @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by internal users on behalf of agency user
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And upload the Proof for Agency Approval-Rejection for the temporary placement
#         And Reject and Revert the temporary placement by internal user on behalf of agency user
#         Then make the agency rejected amendements in the temporary placement
#             | contractorRate | clientRate |
#             | 20             | 40         |
#         And Submit the temporary placement for Agency Approval
#         And Approve the temporary placement on behalf of Agency user
#         * upload the Proof for Client Approval-Rejection for the temporary placement
#         * Approve the temporary placement on behalf of Client user
#         * upload the Proof for Contractor Approval-Rejection for the temporary placement
#         * Accept the temporary placement on behalf of Contractor user
#         Then Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |


#     @focus @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by internal users on behalf of client user
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And upload the Proof for Agency Approval-Rejection for the temporary placement
#         * Approve the temporary placement on behalf of Agency user
#         * upload the Proof for Client Approval-Rejection for the temporary placement
#         * Reject and Revert the temporary placement by internal user on behalf of client user
#         * make the client rejected amendements in the temporary placement
#             | startDate  | endDate    |
#             | 2023-09-02 | 2024-02-01 |
#         * Submit the temporary placement for Agency Approval
#         Then Approve the temporary placement on behalf of Agency user
#         And  Approve the temporary placement on behalf of Client user
#         * upload the Proof for Contractor Approval-Rejection for the temporary placement
#         * Accept the temporary placement on behalf of Contractor user
#         Then Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |


#     @focus  @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by internal users on behalf of contractor user
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And upload the Proof for Agency Approval-Rejection for the temporary placement
#         * Approve the temporary placement on behalf of Agency user
#         * upload the Proof for Client Approval-Rejection for the temporary placement
#         * Approve the temporary placement on behalf of Client user
#         * upload the Proof for Contractor Approval-Rejection for the temporary placement
#         * Reject and Revert the temporary placement by internal user on behalf of contractor user
#         * make the contractor rejected amendements in the temporary placement
#             | contractorRate |
#             | 10             |
#         Then Submit the temporary placement for Agency Approval
#         And Approve the temporary placement on behalf of Agency user
#         * Approve the temporary placement on behalf of Client user
#         * Accept the temporary placement on behalf of Contractor user
#         Then Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |


#     @focus @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by agency user, resubmitted and approved by external users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And Review and Reject the temporary placement by agency user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Revert and Resubmit the temporary placement for Agency approval
#             | contractorRate | clientRate |
#             | 20             | 40         |
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |



#     @focus @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by client hiring manager user, resubmited and approved by external users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         * Review and Approve the temporary placement by agency user
#         * Review and Reject the temporary placement by client hiring manager user
#         * Revert and Resubmit the temporary placement for client approval by agency user
#             | startDate  | endDate    |
#             | 2023-09-02 | 2024-02-01 |
#         * Review and Approve the temporary placement by client hiring manager user
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |


#     @focus @E2E
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by contractor, resubmitted and approved by external users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user
#         Then Review and Reject the temporary placement by contractor user
#         * login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Revert and Resubmit the temporary placement for contractor approval
#             | contractorRate |
#             | 10             |
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |




#     # # <---Client User Approval via magic link--->
#     @focus @E2E @magicLink
#     Scenario Outline: Create a temporary placement for <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and approved by external users (client approval via magic link)
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And Review and Approve the temporary placement by agency user
#         *  Review and Approve the temporary placement by client hiring manager user via magic link
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         Then "<timesheetFrequency>"-"<unitType>" Timesheets should get autogenerated for the "<fundingModel>" model maped entites with funding type as "<fundingType>"
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |

#     @focus @E2E @magicLink
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by contractor, resubmitted and approved by external users (Client approval via magic link)
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user via magic link
#         Then Review and Reject the temporary placement by contractor user
#         * login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Revert and Resubmit the temporary placement for contractor approval
#             | contractorRate |
#             | 10             |
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user via magic link
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType    | fundingModel | unitType | timesheetFrequency |
#             | Funded         | Direct       | Hours    | Weekly             |
#             | Funded         | Direct       | Hours    | Monthly            |
#             | Funded         | Direct       | Days     | Weekly             |
#             | Funded         | Direct       | Days     | Monthly            |
#             | Funded         | Indirect     | Hours    | Weekly             |
#             | Funded         | Indirect     | Hours    | Monthly            |
#             | Funded         | Indirect     | Days     | Weekly             |
#             | Funded         | Indirect     | Days     | Monthly            |
#             | Paid When Paid | Direct       | Hours    | Weekly             |
#             | Paid When Paid | Direct       | Hours    | Monthly            |
#             | Paid When Paid | Direct       | Days     | Weekly             |
#             | Paid When Paid | Direct       | Days     | Monthly            |
#             | Paid When Paid | Indirect     | Hours    | Weekly             |
#             | Paid When Paid | Indirect     | Hours    | Monthly            |
#             | Paid When Paid | Indirect     | Days     | Weekly             |
#             | Paid When Paid | Indirect     | Days     | Monthly            |

#     @focus @E2E @magicLink
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by client hiring manager user, resubmited and approved by external users (Client user approval via magic link)
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         * Review and Approve the temporary placement by agency user
#         * Review and Reject the temporary placement by client hiring manager user via magic link
#         * Revert and Resubmit the temporary placement for client approval by agency user
#             | startDate  | endDate    |
#             | 2023-09-02 | 2024-02-01 |
#         * Review and Approve the temporary placement by client hiring manager user via magic link
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |

#     @focus @E2E @magicLink
#     Scenario Outline: Create a temporary placement for  <timesheetFrequency>-<unitType> with funding type as <fundingType> and funding model as <fundingModel>, reviewed and rejected by agency user, resubmitted and approved by external users (Client user approval via magic link)
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And Review and Reject the temporary placement by agency user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Revert and Resubmit the temporary placement for Agency approval
#             | contractorRate | clientRate |
#             | 20             | 40         |
#         * Review and Approve the temporary placement by agency user
#         * Review and Approve the temporary placement by client hiring manager user via magic link
#         * Review and Accept the temporary placement by contractor user
#         Then login as Onboarding agent Maker user
#         And navigate to the temporary placement list page
#         * select the respective temporary placement
#         * Timesheets should get autogenerated
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Monthly            |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |

#     # Chase the Placement for Pending Client approval by Internal user
#     @focus @E2E
#     Scenario Outline: Ability to chase Pending client approval <timesheetFrequency>-<unitType> temporary placement with funding type as <fundingType> and funding model as <fundingModel> by internal users on behalf of external users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<unitType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         * upload the Proof for Agency Approval-Rejection for the temporary placement
#         And Approve the temporary placement on behalf of Agency user
#         Then navigate to temp placement list page from the placement view page
#         * Filter the ID and chase the Pending client approval
#         * Verify the mail sent to the Hiring manager
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Weekly             |
#     # | Paid When Paid | Direct       | Hours    | Monthly            |
#     # | Paid When Paid | Direct       | Days     | Weekly             |
#     # | Paid When Paid | Direct       | Days     | Monthly            |
#     # | Paid When Paid | Indirect     | Hours    | Weekly             |
#     # | Paid When Paid | Indirect     | Hours    | Monthly            |
#     # | Paid When Paid | Indirect     | Days     | Weekly             |
#     # | Paid When Paid | Indirect     | Days     | Monthly            |

#     # Chase the Placement for Pending Client approval by Agency user
#     @focus @E2E
#     Scenario Outline: Ability to chase Pending client approval <timesheetFrequency>-<unitType> temporary placement with funding type as <fundingType> and funding model as <fundingModel> by agency users
#         Given temporary placement details
#         Then select the funding type "<fundingType>" in temporary placement form
#         And select the currency in the temporary placement form
#         * select the "<fundingModel>" model agency in the temporary placement form
#         * select the "<fundingModel>" model client in the temporary placement form
#         * select the "<fundingModel>" model contractor in the temporary placement form
#         * fill the placement details in the temporary placement form
#         * select the "<timesheetFrequency>" frequency in the temporary placement form
#         * fill the standard rate details according to the unit type-"<unitType>" in the temporary placement form
#         * Add the Additional rate according to the unit type-"<uniteType>" in the temporary placement form, if required
#         Then Submit the temporary placement for Agency Approval
#         And Login as an agency user, approve their placement, and then chase the pending client placement
#         Then navigate to the temporary placement list page
#         * Filter the ID and chase the Pending client approval
#         * Verify the mail sent to the Hiring manager
#         Examples:
#             | fundingType | fundingModel | unitType | timesheetFrequency |
#             | Funded      | Direct       | Hours    | Weekly             |
#             | Funded      | Direct       | Hours    | Monthly            |
#             | Funded      | Direct       | Days     | Weekly             |
#             | Funded      | Direct       | Days     | Monthly            |
#             | Funded      | Indirect     | Hours    | Weekly             |
#             | Funded      | Indirect     | Hours    | Monthly            |
#             | Funded      | Indirect     | Days     | Weekly             |
#             | Funded      | Indirect     | Days     | Weekly             |
# # | Paid When Paid | Direct       | Hours    | Weekly             |
# # | Paid When Paid | Direct       | Hours    | Monthly            |
# # | Paid When Paid | Direct       | Days     | Weekly             |
# # | Paid When Paid | Direct       | Days     | Monthly            |
# # | Paid When Paid | Indirect     | Hours    | Weekly             |
# # | Paid When Paid | Indirect     | Hours    | Monthly            |
# # | Paid When Paid | Indirect     | Days     | Weekly             |
# # | Paid When Paid | Indirect     | Days     | Monthly            |
